#!/usr/bin/dash

wallpaper_dir=$(realpath -e -- "$(xdg-user-dir PICTURES)/wallpaper") \
  || exit 1
wallpaper_dir=${wallpaper_dir#x}

imgfile=$(find "$wallpaper_dir" -type f -print0 \
  | xargs -0 swayimg -g --config=general.overlay=no --)

if [ -z "$imgfile" ]; then
  exit 0
fi

swaymsg output '*' bg "$imgfile" stretch

if [ "$1" = "--persist" ]; then
  ln -sf -- "$imgfile" "$wallpaper_dir/current"
fi
