#!/usr/bin/dash

PROMPT="Workspace: "
[ "$LANG" = zh_CN.UTF-8 ] && PROMPT="工作区名："

workspace=$(swaymsg -rt get_workspaces \
  | fj -r '[*].name' \
  | riced-menu -p "$PROMPT")

swaymsg workspace "$workspace"
