#!/bin/sh

PROMPT="Workspace: "
[ "$LANG" = zh_CN.UTF-8 ] && PROMPT="工作区名："

workspace=$(swaymsg -rt get_workspaces \
  | jq -r '.[].name' \
  | riced-menu -p "$PROMPT")

swaymsg move container to workspace "$workspace"
