#!/bin/sh

if ! wifi-connect-gui; then
  exit 1
fi

i=0
while [ "$i" -le 20 ] && ! wifi-connected; do
  pkill -u "$(id -u)" -USR1 i3status
  # pkill -u "$(id -u)" -RTMIN+3 i3blocks
  i=$((i + 1))
  sleep 0.5
done

pkill -u "$(id -u)" -USR1 i3status
# pkill -s 0 -RTMIN+3 i3blocks
