#!/usr/bin/dash

. "${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/scripts/colors"

bat_sysdir=
for dir in /sys/class/power_supply/*; do
  if [ -d "$dir" ] && [ "$(cat "$dir"/type)" = "Battery" ]; then
    bat_sysdir=$dir
    break
  fi
done

# No battery found. This is not an error, just skip this block.
if [ -z "$bat_sysdir" ]; then
  return 0
fi

status=$(tr 'a-z' 'A-Z' <"$bat_sysdir/status")

charge_now=$(cat "$bat_sysdir/charge_now")
charge_full_design=$(cat "$bat_sysdir/charge_full_design")

permyriad=$((charge_now * 10000 / charge_full_design))
integral_part=${permyriad%??}
if [ "$integral_part" = "100" ]; then
  fractional_part=0
else
  fractional_part=${permyriad#??}
fi

percentage="$integral_part.$fractional_part%"

color=
icon=
if [ "$status" = "CHARGING" -o "$status" = "FULL" ]; then
  icon=🔋
  color=$color_good
elif [ "$permyriad" -gt "2000" ]; then
  icon=🔋
  color=$color_normal
else
  icon=🪫
  color=$color_bad
fi


printf "%s %s %s\n" "$icon" "$status" "$percentage"
printf "%s %s\n" "$icon" "${percentage%\%}"
echo $color
