#!/usr/bin/dash

. "${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/scripts/colors"

: ${button:-0}
case "$button" in
  4)
    audioctl set pvolume 2%+ >/dev/null 2>&1
    ;;
  5)
    audioctl set pvolume 2%- >/dev/null 2>&1
    ;;
  2)
    audioctl set pswitch toggle >/dev/null 2>&1
    ;;
  1)
    verbose=1
    ;;
esac

status=

{
  IFS= read -r line
  scontrol=${line#Simple mixer control }
  if [ -z "$verbose" ]; then
    scontrol=${scontrol#*\'}
    scontrol=${scontrol%\'*}
  fi
  while IFS= read -r line; do
    case "$line" in
      *Playback*\[*\]*\[*\]*\[*\]*)
        if [ -z "$verbose" ]; then
          status=$(printf "%s" "$line" | \
            sed -E 's/^.*\[(.*)\]\s*\[.*\]\s*\[(.*)\]$/\1 \2/')
          break
        else
          status=$status${status:+, }$(printf "%s" "$line" | \
            sed -E 's/^\s*(.*):.*\[(.*)\]\s*\[.*\]\s*\[(.*)\]$/\1: \2 \3/')
        fi
        ;;
    esac
  done
} <<EOF
$(audioctl get pvolume)
EOF


icon=🔇
color=$color_normal

case "$status" in
  *off*)
    color=$color_bad
    ;;
  *)
    volume=${status% *}
    if [ -n "$verbose" ]; then
      volume=$(printf "%s" "$status" | grep -o '[[:digit:]]*' | \
        {
          max=0
          while read num; do
            max=$((num > max ? num : max))
          done
          printf "%u" "$max"
        })%
    fi

    case "$volume" in
      [0-3]?%|[0-9]%)
        icon=🔈
        ;;
      [4-7]?%)
        icon=🔉
        ;;
      [8-9]?%|100%)
        icon=🔊
        ;;
    esac
    ;;
esac

printf "%s %s %s\n" "$icon" "$scontrol" "$status"
printf "%s %s\n" "$icon" "$status"
echo "$color"
