#!/usr/bin/dash

. "${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/scripts/colors"

configdir="${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/scripts/config"
if ! [ -f "$configdir/wireless" ]; then
  mkdir -p "$configdir"
  for interface in /sys/class/net/*; do
    [ -d "$interface" ] || continue
    if [ -d "$interface/wireless" ]; then
      interface=${interface##*/}
      printf "interface=%s\n# vim: ft=sh\n" "$interface" >"$configdir/wireless"
      break
    fi
  done

  if ! [ -f "$configdir/wireless" ]; then
    printf "interface=\n# vim: ft=sh\n" >"$configdir/wireless"
  fi
fi

. "$configdir/wireless"

if [ -z "$interface" ]; then
  exit 0
fi

: ${button:=-1}
if [ "$button" -eq 1 ]; then
  verbose=true
fi

phyx=$(cat "/sys/class/net/$interface/phy80211/index")
ifindex=$(cat "/sys/class/net/$interface/ifindex")

icon=🛜

dbus_response=$(busctl --json short --system call \
  net.connman.iwd \
  "/net/connman/iwd/$phyx/$ifindex" \
  org.freedesktop.DBus.Properties \
  GetAll \
  "s" net.connman.iwd.Station 2>/dev/null)

if [ "$?" -ne 0 ]; then
  exit 0
fi

status=$(printf "%s" "$dbus_response" \
  | fj -r '.data[0].State.data' \
  | tr 'a-z' 'A-Z')

ssid=$(busctl --json short --system get-property \
  net.connman.iwd \
  "$(printf "%s" "$dbus_response" | fj -r '.data[0].ConnectedNetwork.data')" \
  net.connman.iwd.Network \
  Name 2>/dev/null | fj -r '.data')

case "$status" in
  CONNECTED)
    color=$color_good
    ;;
  DISCONNECTED)
    color=$color_bad
    ;;
  *)
    color=$color_normal
    ;;
esac


if [ -n "$verbose" ]; then
  printf "%s %s %s" "$icon" "$interface" "$status"
  [ -n "$ssid" ] && printf " %s" "$ssid"

  ip -o addr show "$interface" 2>/dev/null | awk '{print $4}' | \
    while IFS= read -r addr; do
      printf " %s" "$addr"
    done

  echo
else
  printf "%s %s" "$icon" "$status"
  [ -n "$ssid" ] && printf " %s" "$ssid"
  echo
fi

printf "%s" "$icon"
[ -n "$ssid" ] && printf " %s" "$ssid"
echo

echo "$color"
