#!/bin/sh

call() {
  cat -- "$(jq -r ".path" <"$1")"
}

case "$1" in
  call)
    call "$2"
    ;;
  description)
    printf '"Output the content of a given file."'
    ;;
  parameters)
    printf '{
      "path": {
        "type": "string",
        "description": "The file path."
      }
    }'
    ;;
  *)
    printf "Unknown subcommand: %s\n" "$1" >&2
    ;;
esac

