#!/bin/sh

call() {
  curl -sS -- "$(jq -r ".url")" 2>&1
}

case "$1" in
  call)
    call
    ;;
  description)
    printf '"Get a web page"'
    ;;
  parameters)
    printf '{
      "url": {
        "type": "string",
        "description": "the website url"
      }
    }'
    ;;
  *)
    printf "Unknown subcommand: %s\n" "$1" >&2
    ;;
esac

