#!/bin/sh

call() {
  tz=$(jq -r ".timezone" <"$1")
  if [ "$tz" = UTC ]; then
    date -u
  else
    date
  fi
}

case "$1" in
  call)
    call "$2"
    ;;
  description)
    printf '"Get current date and time."'
    ;;
  parameters)
    printf '{
      "timezone": {
        "type": "string",
        "description": "CST or UTC."
      }
    }'
    ;;
  *)
    printf "Unknown subcommand: %s\n" "$1" >&2
    ;;
esac
