#!/bin/sh

call() {
  tmpfile=$(tmpfile)

  jq -r '.code' <"$1" >"$tmpfile"

  printf "\033[31mRUN SCRIPT:33[0m\n"
  tr '\n' '\000' <"$tmpfile" | xargs -r0 printf "\033[1;31m|\033[0m \033[32;1m%s\033[0m\n" >&2
  klang -- "$tmpfile" 2>&1
  rm "$tmpfile"
}

case "$1" in
  call)
    call "$2"
    ;;
  description)
    printf '"Execute klang script and output its result."'
    ;;
  parameters)
    printf '{
      "code": {
        "type": "string",
        "description": "klang script code to to executed."
      }
    }'
    ;;
  *)
    printf "Unknown subcommand: %s\n" "$1" >&2
    ;;
esac

