#!/bin/sh

call() {
  tmpfile_base=${XDG_RUNTIME_DIR:?"XDG_RUNTIME_DIR is not defined"}/llm-chat-tools.klang.tmp.$$
  i=0
  tmpfile=$tmpfile.$i
  while ! (set -C; : >"$tmpfile"); do
    i=$((i + 1))
    tmpfile=$tmpfile.$i
  done

  jq -r '.code' <"$1" >"$tmpfile"
  klang -- "$tmpfile" 2>&1
  rm "$tmpfile"
}

case "$1" in
  call)
    call "$2"
    ;;
  description)
    printf '"Execute klang script and output its result."'
    ;;
  parameters)
    printf '{
      "code": {
        "type": "string",
        "description": "klang script code to to executed."
      }
    }'
    ;;
  *)
    printf "Unknown subcommand: %s\n" "$1" >&2
    ;;
esac

