#!/bin/sh

call() {
  item=$(jq -r '.args' <"$1")
  if ! man -- $item >/dev/null 2>&1; then
    printf "Can not find manual page for item: %s\n" "$item"
  else
    man -- $item 2>/dev/null
  fi
}

case "$1" in
  call)
    call "$2"
    ;;
  description)
    printf '"Get manual page(i.e. call man utility)"'
    ;;
  parameters)
    printf '{
      "args": {
        "type": "string",
        "description": "The arguments to be appended to `man --` to form a command."
      }
    }'
    ;;
  *)
    printf "Unknown subcommand: %s\n" "$1" >&2
    ;;
esac

