#!/usr/bin/bash

shopt -s extglob

file=$(realpath -- "$1") || exit 1
mime_type=$(file --mime-type --brief -- "$file" </dev/null)
printf "%s\n" "$mime_type"
case "$mime_type" in
  text/plain)
    cat -- "$file"
    ;;
  @(application/@(yaml|toml|json)|text/*))
    highlight -O ansi -- "$file"
    ;;
  *)
    content=$(file --brief -- "$file")
    length=${#content}
    width=$(($2 - 3))
    if [ "$width" -le 0 ]; then
      exit
    fi
    for ((i = 0; i < length; i += this_width)); do
      this_width=$((i + width < length ? width : length - i))
      printf "%s\n" "${content:$i:$this_width}"
    done
    ;;
esac
