#!/bin/sh

# Assume that there are no empty line
make_result() {
  IFS= read -r line
  if [ -z "$line" ]; then
    printf "%s\n" "No matchs found"
    exit 1
  else
    printf "%s\n" "Found"
    printf "%s\n" "$line"
    exec cat
  fi
}

gpg -q --decrypt -- "$(xdg-user-dir DOCUMENTS)"/addressbook.gpg 2>/dev/null \
  | tail -n +2 2>/dev/null \
  | fuzzy-query "$1" 2>/dev/null \
  | make_result
