#!/bin/sh

case $(termcolors) in
  256)
    break
    ;;
  *)
    printf "%s\n " "$(termcolors)"
    exit
    ;;
esac

: ${XDG_STATE_HOME:=$HOME/.local/state}
COLOR_THEME_FILE=$XDG_STATE_HOME/colorscheme/neomutt/current_theme

if [ ! -r "$COLOR_THEME_FILE" ]; then
  printf "256-dark\n"
  exit
fi

printf "%s\n" "$(cat -- "$COLOR_THEME_FILE")"
